function Pij = MUSTEM_P37(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_P37
%    PIJ = MUSTEM_P37(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:26:46

t2 = -Theta3;
t3 = -Theta4;
t4 = -Theta5;
t5 = -Theta6;
t6 = exp(t2);
t7 = exp(t3);
t8 = exp(t4);
t9 = Theta3+t3;
t10 = Theta3+t4;
t11 = Theta3+t5;
t12 = Theta4+t4;
t13 = Theta4+t5;
t14 = Theta5+t5;
t15 = 1.0./t9;
t16 = 1.0./t10;
t17 = 1.0./t11;
t18 = 1.0./t12;
t19 = 1.0./t13;
t20 = 1.0./t14;
Pij = -t6+Theta3.*t6.*t15+t2.*t7.*t15+Theta3.*Theta4.*t7.*t15.*t18+Theta4.*t2.*t6.*t15.*t16+Theta4.*t2.*t8.*t16.*t18+Theta3.*Theta4.*Theta5.*t6.*t15.*t16.*t17+Theta3.*Theta4.*Theta5.*t8.*t16.*t18.*t20+Theta4.*Theta5.*t2.*t7.*t15.*t18.*t19+Theta4.*Theta5.*t2.*t17.*t19.*t20.*exp(t5)+1.0;
