function Pij = MUSTEM_P46(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_P46
%    PIJ = MUSTEM_P46(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:27:21

t2 = -Theta5;
t3 = -Theta6;
t4 = Theta4+t2;
t5 = Theta4+t3;
t6 = Theta5+t3;
t7 = 1.0./t4;
t8 = 1.0./t5;
t9 = 1.0./t6;
Pij = Theta4.*Theta5.*t7.*t8.*exp(-Theta4)+Theta4.*Theta5.*t8.*t9.*exp(t3)+Theta4.*t2.*t7.*t9.*exp(t2);
