function out1 = MUSTEM_12_f_prime_1(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_12_F_PRIME_1
%    OUT1 = MUSTEM_12_F_PRIME_1(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:16:31

t2 = -Theta1;
t3 = -Theta2;
t4 = exp(t2);
t5 = exp(t3);
t6 = Theta1+t3;
t7 = 1.0./t6;
t8 = t7.^2;
t9 = Theta1.*t4.*t7;
out1 = -(t9-t4.*t7+t5.*t7+Theta1.*t4.*t8+t2.*t5.*t8)./(t9+t2.*t5.*t7);
