function out1 = MUSTEM_16_f_prime_2(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_16_F_PRIME_2
%    OUT1 = MUSTEM_16_F_PRIME_2(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:17:48

t2 = -Theta1;
t3 = -Theta2;
t4 = -Theta3;
t5 = -Theta4;
t6 = -Theta5;
t7 = -Theta6;
t8 = exp(t2);
t9 = exp(t3);
t10 = exp(t4);
t11 = exp(t5);
t12 = exp(t6);
t13 = exp(t7);
t14 = Theta1+t3;
t15 = Theta1+t4;
t16 = Theta1+t5;
t17 = Theta2+t4;
t18 = Theta1+t6;
t19 = Theta2+t5;
t20 = Theta1+t7;
t21 = Theta2+t6;
t22 = Theta3+t5;
t23 = Theta2+t7;
t24 = Theta3+t6;
t25 = Theta3+t7;
t26 = Theta4+t6;
t27 = Theta4+t7;
t28 = Theta5+t7;
t29 = 1.0./t14;
t31 = 1.0./t15;
t32 = 1.0./t16;
t33 = 1.0./t17;
t35 = 1.0./t18;
t36 = 1.0./t19;
t38 = 1.0./t20;
t39 = 1.0./t21;
t40 = 1.0./t22;
t42 = 1.0./t23;
t43 = 1.0./t24;
t45 = 1.0./t25;
t46 = 1.0./t26;
t47 = 1.0./t27;
t48 = 1.0./t28;
t30 = t29.^2;
t34 = t33.^2;
t37 = t36.^2;
t41 = t39.^2;
t44 = t42.^2;
t49 = Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t9.*t29.*t33.*t36.*t39.*t42;
out1 = (t49+Theta1.*Theta3.*Theta4.*Theta5.*t8.*t29.*t31.*t32.*t35.*t38+Theta1.*Theta3.*Theta4.*Theta5.*t10.*t31.*t33.*t40.*t43.*t45+Theta1.*Theta3.*Theta4.*Theta5.*t12.*t35.*t39.*t43.*t46.*t48+Theta3.*Theta4.*Theta5.*t2.*t9.*t29.*t33.*t36.*t39.*t42+Theta3.*Theta4.*Theta5.*t2.*t11.*t32.*t36.*t40.*t46.*t47+Theta3.*Theta4.*Theta5.*t2.*t13.*t38.*t42.*t45.*t47.*t48+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t8.*t30.*t31.*t32.*t35.*t38+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t9.*t29.*t33.*t37.*t39.*t42+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t9.*t29.*t34.*t36.*t39.*t42+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t9.*t29.*t33.*t36.*t39.*t44+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t9.*t29.*t33.*t36.*t41.*t42+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t11.*t32.*t37.*t40.*t46.*t47+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t13.*t38.*t44.*t45.*t47.*t48+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t9.*t30.*t33.*t36.*t39.*t42+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t10.*t31.*t34.*t40.*t43.*t45+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t12.*t35.*t41.*t43.*t46.*t48)./(Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t8.*t29.*t31.*t32.*t35.*t38+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t10.*t31.*t33.*t40.*t43.*t45+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t12.*t35.*t39.*t43.*t46.*t48+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t9.*t29.*t33.*t36.*t39.*t42+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t11.*t32.*t36.*t40.*t46.*t47+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t13.*t38.*t42.*t45.*t47.*t48);
