function out1 = MUSTEM_27_f_prime_5(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_27_F_PRIME_5
%    OUT1 = MUSTEM_27_F_PRIME_5(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:24:54

t2 = -Theta2;
t3 = -Theta3;
t4 = -Theta4;
t5 = -Theta5;
t6 = -Theta6;
t7 = exp(t2);
t8 = exp(t3);
t9 = exp(t4);
t10 = exp(t5);
t11 = exp(t6);
t12 = Theta2+t3;
t13 = Theta2+t4;
t14 = Theta2+t5;
t15 = Theta3+t4;
t16 = Theta2+t6;
t17 = Theta3+t5;
t18 = Theta3+t6;
t19 = Theta4+t5;
t20 = Theta4+t6;
t21 = Theta5+t6;
t22 = 1.0./t12;
t23 = 1.0./t13;
t24 = 1.0./t14;
t25 = 1.0./t15;
t27 = 1.0./t16;
t28 = 1.0./t17;
t30 = 1.0./t18;
t31 = 1.0./t19;
t33 = 1.0./t20;
t34 = 1.0./t21;
t26 = t24.^2;
t29 = t28.^2;
t32 = t31.^2;
t35 = t34.^2;
t36 = Theta2.*Theta3.*Theta4.*t10.*t24.*t28.*t31;
t37 = Theta5.*t34.*t36;
out1 = (t37+Theta5.*t35.*t36+Theta2.*Theta3.*Theta4.*t8.*t22.*t25.*t29+Theta2.*Theta3.*Theta4.*t10.*t24.*t28.*t32+Theta2.*Theta3.*Theta4.*t10.*t24.*t29.*t31+Theta2.*Theta3.*Theta4.*t10.*t26.*t28.*t31+Theta3.*Theta4.*t2.*t7.*t22.*t23.*t26+Theta3.*Theta4.*t2.*t9.*t23.*t25.*t32+Theta3.*Theta4.*t2.*t10.*t24.*t28.*t31+Theta2.*Theta3.*Theta4.*t7.*t22.*t23.*t24.*t27+Theta2.*Theta3.*Theta4.*t9.*t23.*t25.*t31.*t33+Theta2.*Theta3.*Theta4.*t11.*t27.*t30.*t33.*t34+Theta3.*Theta4.*t2.*t8.*t22.*t25.*t28.*t30+Theta3.*Theta4.*t2.*t10.*t24.*t28.*t31.*t34+Theta3.*Theta4.*Theta5.*t2.*t8.*t22.*t25.*t29.*t30+Theta3.*Theta4.*Theta5.*t2.*t10.*t24.*t28.*t32.*t34+Theta3.*Theta4.*Theta5.*t2.*t10.*t24.*t29.*t31.*t34+Theta3.*Theta4.*Theta5.*t2.*t10.*t26.*t28.*t31.*t34+Theta3.*Theta4.*Theta5.*t2.*t11.*t27.*t30.*t33.*t35+Theta2.*Theta3.*Theta4.*Theta5.*t7.*t22.*t23.*t26.*t27+Theta2.*Theta3.*Theta4.*Theta5.*t9.*t23.*t25.*t32.*t33)./(t7+t36+Theta2.*t8.*t22+t2.*t7.*t22+Theta2.*Theta3.*t7.*t22.*t23+Theta2.*Theta3.*t9.*t23.*t25+Theta3.*t2.*t8.*t22.*t25+Theta2.*Theta3.*Theta4.*t8.*t22.*t25.*t28+Theta3.*Theta4.*t2.*t7.*t22.*t23.*t24+Theta3.*Theta4.*t2.*t9.*t23.*t25.*t31+Theta3.*Theta4.*Theta5.*t2.*t8.*t22.*t25.*t28.*t30+Theta3.*Theta4.*Theta5.*t2.*t10.*t24.*t28.*t31.*t34+Theta2.*Theta3.*Theta4.*Theta5.*t7.*t22.*t23.*t24.*t27+Theta2.*Theta3.*Theta4.*Theta5.*t9.*t23.*t25.*t31.*t33+Theta2.*Theta3.*Theta4.*Theta5.*t11.*t27.*t30.*t33.*t34-1.0);
