function out1 = MUSTEM_67_f_prime_6(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_67_F_PRIME_6
%    OUT1 = MUSTEM_67_F_PRIME_6(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:28:00

t2 = -Theta6;
t3 = exp(t2);
out1 = -t3./(t3-1.0);
