function Pij = MUSTEM_P27(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_P27
%    PIJ = MUSTEM_P27(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:24:52

t2 = -Theta2;
t3 = -Theta3;
t4 = -Theta4;
t5 = -Theta5;
t6 = -Theta6;
t7 = exp(t2);
t8 = exp(t3);
t9 = exp(t4);
t10 = exp(t5);
t11 = Theta2+t3;
t12 = Theta2+t4;
t13 = Theta2+t5;
t14 = Theta3+t4;
t15 = Theta2+t6;
t16 = Theta3+t5;
t17 = Theta3+t6;
t18 = Theta4+t5;
t19 = Theta4+t6;
t20 = Theta5+t6;
t21 = 1.0./t11;
t22 = 1.0./t12;
t23 = 1.0./t13;
t24 = 1.0./t14;
t25 = 1.0./t15;
t26 = 1.0./t16;
t27 = 1.0./t17;
t28 = 1.0./t18;
t29 = 1.0./t19;
t30 = 1.0./t20;
Pij = -t7+Theta2.*t7.*t21+t2.*t8.*t21+Theta2.*Theta3.*t8.*t21.*t24+Theta3.*t2.*t7.*t21.*t22+Theta3.*t2.*t9.*t22.*t24+Theta2.*Theta3.*Theta4.*t7.*t21.*t22.*t23+Theta2.*Theta3.*Theta4.*t9.*t22.*t24.*t28+Theta3.*Theta4.*t2.*t8.*t21.*t24.*t26+Theta3.*Theta4.*t2.*t10.*t23.*t26.*t28+Theta3.*Theta4.*Theta5.*t2.*t7.*t21.*t22.*t23.*t25+Theta3.*Theta4.*Theta5.*t2.*t9.*t22.*t24.*t28.*t29+Theta3.*Theta4.*Theta5.*t2.*t25.*t27.*t29.*t30.*exp(t6)+Theta2.*Theta3.*Theta4.*Theta5.*t8.*t21.*t24.*t26.*t27+Theta2.*Theta3.*Theta4.*Theta5.*t10.*t23.*t26.*t28.*t30+1.0;
