function Pij = MUSTEM_P15(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_P15
%    PIJ = MUSTEM_P15(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:17:01

t2 = -Theta2;
t3 = -Theta3;
t4 = -Theta4;
t5 = -Theta5;
t6 = Theta1+t2;
t7 = Theta1+t3;
t8 = Theta1+t4;
t9 = Theta2+t3;
t10 = Theta1+t5;
t11 = Theta2+t4;
t12 = Theta2+t5;
t13 = Theta3+t4;
t14 = Theta3+t5;
t15 = Theta4+t5;
t16 = 1.0./t6;
t17 = 1.0./t7;
t18 = 1.0./t8;
t19 = 1.0./t9;
t20 = 1.0./t10;
t21 = 1.0./t11;
t22 = 1.0./t12;
t23 = 1.0./t13;
t24 = 1.0./t14;
t25 = 1.0./t15;
Pij = Theta1.*Theta2.*Theta3.*Theta4.*t17.*t19.*t23.*t24.*exp(t3)+Theta1.*Theta2.*Theta3.*Theta4.*t20.*t22.*t24.*t25.*exp(t5)+Theta1.*Theta3.*Theta4.*t2.*t16.*t19.*t21.*t22.*exp(t2)+Theta1.*Theta3.*Theta4.*t2.*t18.*t21.*t23.*t25.*exp(t4)+Theta1.*Theta2.*Theta3.*Theta4.*t16.*t17.*t18.*t20.*exp(-Theta1);
