function Pij = MUSTEM_P35(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_P35
%    PIJ = MUSTEM_P35(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:26:20

t2 = -Theta4;
t3 = -Theta5;
t4 = Theta3+t2;
t5 = Theta3+t3;
t6 = Theta4+t3;
t7 = 1.0./t4;
t8 = 1.0./t5;
t9 = 1.0./t6;
Pij = Theta3.*Theta4.*t7.*t8.*exp(-Theta3)+Theta3.*Theta4.*t8.*t9.*exp(t3)+Theta3.*t2.*t7.*t9.*exp(t2);
