function out1 = MUSTEM_56_f_prime_3(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_56_F_PRIME_3
%    OUT1 = MUSTEM_56_F_PRIME_3(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:27:43

out1 = 0.0;
