function Pij = MUSTEM_P17(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_P17
%    PIJ = MUSTEM_P17(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:19:45

t2 = -Theta1;
t3 = -Theta2;
t4 = -Theta3;
t5 = -Theta4;
t6 = -Theta5;
t7 = -Theta6;
t8 = exp(t2);
t9 = exp(t3);
t10 = exp(t4);
t11 = exp(t5);
t12 = exp(t6);
t13 = Theta1+t3;
t14 = Theta1+t4;
t15 = Theta1+t5;
t16 = Theta2+t4;
t17 = Theta1+t6;
t18 = Theta2+t5;
t19 = Theta1+t7;
t20 = Theta2+t6;
t21 = Theta3+t5;
t22 = Theta2+t7;
t23 = Theta3+t6;
t24 = Theta3+t7;
t25 = Theta4+t6;
t26 = Theta4+t7;
t27 = Theta5+t7;
t28 = 1.0./t13;
t29 = 1.0./t14;
t30 = 1.0./t15;
t31 = 1.0./t16;
t32 = 1.0./t17;
t33 = 1.0./t18;
t34 = 1.0./t19;
t35 = 1.0./t20;
t36 = 1.0./t21;
t37 = 1.0./t22;
t38 = 1.0./t23;
t39 = 1.0./t24;
t40 = 1.0./t25;
t41 = 1.0./t26;
t42 = 1.0./t27;
Pij = -t8+Theta1.*t8.*t28+t2.*t9.*t28+Theta1.*Theta2.*t9.*t28.*t31+Theta2.*t2.*t8.*t28.*t29+Theta2.*t2.*t10.*t29.*t31+Theta1.*Theta2.*Theta3.*t8.*t28.*t29.*t30+Theta1.*Theta2.*Theta3.*t10.*t29.*t31.*t36+Theta2.*Theta3.*t2.*t9.*t28.*t31.*t33+Theta2.*Theta3.*t2.*t11.*t30.*t33.*t36+Theta2.*Theta3.*Theta4.*t2.*t8.*t28.*t29.*t30.*t32+Theta2.*Theta3.*Theta4.*t2.*t10.*t29.*t31.*t36.*t38+Theta2.*Theta3.*Theta4.*t2.*t12.*t32.*t35.*t38.*t40+Theta1.*Theta2.*Theta3.*Theta4.*t9.*t28.*t31.*t33.*t35+Theta1.*Theta2.*Theta3.*Theta4.*t11.*t30.*t33.*t36.*t40+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t34.*t37.*t39.*t41.*t42.*exp(t7)+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t8.*t28.*t29.*t30.*t32.*t34+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t10.*t29.*t31.*t36.*t38.*t39+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t12.*t32.*t35.*t38.*t40.*t42+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t9.*t28.*t31.*t33.*t35.*t37+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t11.*t30.*t33.*t36.*t40.*t41+1.0;
