function out1 = MUSTEM_14_f_prime_6(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_14_F_PRIME_6
%    OUT1 = MUSTEM_14_F_PRIME_6(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:16:45

out1 = 0.0;
