function out1 = MUSTEM_33_f_prime_2(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_33_F_PRIME_2
%    OUT1 = MUSTEM_33_F_PRIME_2(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:26:09

out1 = 0.0;
