function out1 = MUSTEM_16_f_prime_5(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_16_F_PRIME_5
%    OUT1 = MUSTEM_16_F_PRIME_5(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:17:50

t2 = -Theta1;
t3 = -Theta2;
t4 = -Theta3;
t5 = -Theta4;
t6 = -Theta5;
t7 = -Theta6;
t8 = exp(t2);
t9 = exp(t3);
t10 = exp(t4);
t11 = exp(t5);
t12 = exp(t6);
t13 = exp(t7);
t14 = Theta1+t3;
t15 = Theta1+t4;
t16 = Theta1+t5;
t17 = Theta2+t4;
t18 = Theta1+t6;
t19 = Theta2+t5;
t20 = Theta1+t7;
t21 = Theta2+t6;
t22 = Theta3+t5;
t23 = Theta2+t7;
t24 = Theta3+t6;
t25 = Theta3+t7;
t26 = Theta4+t6;
t27 = Theta4+t7;
t28 = Theta5+t7;
t29 = 1.0./t14;
t30 = 1.0./t15;
t31 = 1.0./t16;
t32 = 1.0./t17;
t33 = 1.0./t18;
t34 = 1.0./t19;
t36 = 1.0./t20;
t37 = 1.0./t21;
t38 = 1.0./t22;
t40 = 1.0./t23;
t41 = 1.0./t24;
t43 = 1.0./t25;
t44 = 1.0./t26;
t46 = 1.0./t27;
t47 = 1.0./t28;
t35 = t33.^2;
t39 = t37.^2;
t42 = t41.^2;
t45 = t44.^2;
t48 = t47.^2;
t49 = Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t12.*t33.*t37.*t41.*t44.*t47;
out1 = (Theta1.*Theta2.*Theta3.*Theta4.*t8.*t29.*t30.*t31.*t33.*t36+Theta1.*Theta2.*Theta3.*Theta4.*t10.*t30.*t32.*t38.*t41.*t43+Theta1.*Theta2.*Theta3.*Theta4.*t12.*t33.*t37.*t41.*t44.*t47+Theta2.*Theta3.*Theta4.*t2.*t9.*t29.*t32.*t34.*t37.*t40+Theta2.*Theta3.*Theta4.*t2.*t11.*t31.*t34.*t38.*t44.*t46+Theta2.*Theta3.*Theta4.*t2.*t13.*t36.*t40.*t43.*t46.*t47+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t8.*t29.*t30.*t31.*t35.*t36+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t10.*t30.*t32.*t38.*t42.*t43+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t12.*t33.*t37.*t41.*t45.*t47+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t12.*t33.*t37.*t42.*t44.*t47+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t12.*t33.*t39.*t41.*t44.*t47+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t12.*t35.*t37.*t41.*t44.*t47+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t13.*t36.*t40.*t43.*t46.*t48+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t9.*t29.*t32.*t34.*t39.*t40+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t11.*t31.*t34.*t38.*t45.*t46+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t12.*t33.*t37.*t41.*t44.*t47+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t12.*t33.*t37.*t41.*t44.*t48)./(t49+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t8.*t29.*t30.*t31.*t33.*t36+Theta1.*Theta2.*Theta3.*Theta4.*Theta5.*t10.*t30.*t32.*t38.*t41.*t43+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t9.*t29.*t32.*t34.*t37.*t40+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t11.*t31.*t34.*t38.*t44.*t46+Theta2.*Theta3.*Theta4.*Theta5.*t2.*t13.*t36.*t40.*t43.*t46.*t47);
