function Pij = MUSTEM_P67(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_P67
%    PIJ = MUSTEM_P67(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:27:59

Pij = -exp(-Theta6)+1.0;
