function out1 = MUSTEM_26_f_prime_1(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_26_F_PRIME_1
%    OUT1 = MUSTEM_26_F_PRIME_1(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:24:04

out1 = 0.0;
