function Pij = MUSTEM_P57(Theta1,Theta2,Theta3,Theta4,Theta5,Theta6)
%MUSTEM_P57
%    PIJ = MUSTEM_P57(THETA1,THETA2,THETA3,THETA4,THETA5,THETA6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 10:27:49

t2 = -Theta5;
t3 = -Theta6;
t4 = exp(t2);
t5 = Theta5+t3;
t6 = 1.0./t5;
Pij = -t4+t2.*t6.*exp(t3)+Theta5.*t4.*t6+1.0;
